USE [master]
GO

/****** Object:  Database [?dvertisementSystem]    Script Date: 8/13/2016 11:52:49 AM ******/
CREATE DATABASE [?dvertisementSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'?dvertisementSystem', FILENAME = N'C:\Users\eqino\?dvertisementSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'?dvertisementSystem_log', FILENAME = N'C:\Users\eqino\?dvertisementSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [?dvertisementSystem] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [?dvertisementSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [?dvertisementSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [?dvertisementSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [?dvertisementSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [?dvertisementSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [?dvertisementSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [?dvertisementSystem] SET  MULTI_USER 
GO

ALTER DATABASE [?dvertisementSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [?dvertisementSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [?dvertisementSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [?dvertisementSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [?dvertisementSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [?dvertisementSystem] SET QUERY_STORE = OFF
GO

USE [?dvertisementSystem]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [?dvertisementSystem] SET  READ_WRITE 
GO
