USE [master]
GO

/****** Object:  Database [AdvertisementSystem]    Script Date: 8/13/2016 12:07:41 PM ******/
CREATE DATABASE [AdvertisementSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdvertisementSystem', FILENAME = N'C:\Users\eqino\AdvertisementSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdvertisementSystem_log', FILENAME = N'C:\Users\eqino\AdvertisementSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AdvertisementSystem] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdvertisementSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdvertisementSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdvertisementSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdvertisementSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdvertisementSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdvertisementSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdvertisementSystem] SET  MULTI_USER 
GO

ALTER DATABASE [AdvertisementSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdvertisementSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdvertisementSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdvertisementSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AdvertisementSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdvertisementSystem] SET QUERY_STORE = OFF
GO

USE [AdvertisementSystem]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [AdvertisementSystem] SET  READ_WRITE 
GO

